name: Broken link check
on:
  page_build:
  pull_request:
    branches: [ main ]

jobs:
  broken_link_checker_job:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - run: pip3 install linkchecker
    - name: Link Checker
      id: link-report
      run: linkchecker -ofailures --check-extern --ignore-url="\s*\.md" https://hupo-psi.github.io/mzQC/
    - name: Get the result
      run: echo linkchecker/failures
